import React, { useState } from 'react';
import axios from 'axios';
import { Save, ArrowLeft, Plus, Trash2, FileText, Upload, Settings, CheckSquare, Square, Image } from 'lucide-react';
import { toast } from 'react-hot-toast';

export default function ChatFormEditor({ form, onBack }) {
    const [data, setData] = useState(form || {
        name: '',
        trigger_keyword: '',
        is_active: true,
        steps: [{ question: 'Halo! Siapa nama Anda?', label: 'Nama', validation: 'text' }],
        pdf_config: { 
            enabled: false, 
            title: 'BUKTI PENDAFTARAN', 
            footer_text: 'Generated by System',
            layout: 'portrait', // portrait, card_landscape, ticket
            enable_reg_number: true,
            logo_url: '',
            qr_enabled: false,
            qr_field: '',
            fields_to_print: [] // Array of labels
        }
    });

    const handleStepChange = (idx, field, val) => {
        const newSteps = [...data.steps];
        newSteps[idx][field] = val;
        setData({ ...data, steps: newSteps });
    };

    const addStep = () => {
        setData({
            ...data,
            steps: [...data.steps, { question: '', label: '', validation: 'text' }]
        });
    };

    const removeStep = (idx) => {
        setData({ ...data, steps: data.steps.filter((_, i) => i !== idx) });
    };

    const handleSave = async () => {
        if (!data.name || !data.trigger_keyword || data.steps.length === 0) return toast.error("Please fill required fields");
        try {
            if (data.id) {
                await axios.put(`/api/app/forms/${data.id}`, data);
            } else {
                await axios.post('/api/app/forms', data);
            }
            toast.success("Saved");
            onBack();
        } catch (err) {
            toast.error(err.response?.data?.error || "Error saving");
        }
    };

    const handleLogoUpload = async (e) => {
        const file = e.target.files[0];
        if (!file) return;
        const formData = new FormData();
        formData.append('file', file);
        try {
            const res = await axios.post('/api/app/inbox/upload', formData, { headers: {'Content-Type': 'multipart/form-data'}});
            setData({...data, pdf_config: {...data.pdf_config, logo_url: res.data.url}});
        } catch (err) { toast.error("Upload failed"); }
    };

    const toggleFieldPrint = (label) => {
        const current = data.pdf_config.fields_to_print || [];
        const isSelected = current.includes(label);
        const newFields = isSelected ? current.filter(f => f !== label) : [...current, label];
        setData({...data, pdf_config: {...data.pdf_config, fields_to_print: newFields}});
    };

    return (
        <div className="p-4 sm:p-6 md:p-8 h-full overflow-y-auto">
            <div className="flex justify-between items-center mb-6">
                <button onClick={onBack} className="flex items-center text-gray-600 hover:text-gray-900 font-bold">
                    <ArrowLeft className="w-4 h-4 mr-2" /> Back
                </button>
                <button onClick={handleSave} className="px-6 py-2 bg-indigo-600 text-white rounded-lg font-bold flex items-center gap-2 hover:bg-indigo-700">
                    <Save className="w-4 h-4" /> Save Form
                </button>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
                <div className="lg:col-span-2 space-y-6">
                    <div className="bg-white p-6 rounded-xl border shadow-sm">
                        <h3 className="font-bold mb-4 text-gray-800">Basic Info</h3>
                        <div className="grid grid-cols-2 gap-4">
                            <div>
                                <label className="block text-xs font-bold text-gray-500 uppercase mb-1">Form Name</label>
                                <input className="w-full border p-2 rounded" value={data.name} onChange={e=>setData({...data, name: e.target.value})} placeholder="Pendaftaran Member" />
                            </div>
                            <div>
                                <label className="block text-xs font-bold text-gray-500 uppercase mb-1">Trigger Keyword</label>
                                <input className="w-full border p-2 rounded" value={data.trigger_keyword} onChange={e=>setData({...data, trigger_keyword: e.target.value})} placeholder="daftar" />
                            </div>
                        </div>
                    </div>

                    <div className="bg-white p-6 rounded-xl border shadow-sm">
                        <h3 className="font-bold mb-4 text-gray-800">Questions Flow</h3>
                        <div className="space-y-4">
                            {data.steps.map((step, idx) => (
                                <div key={idx} className="flex gap-4 items-start bg-gray-50 p-4 rounded-lg border border-gray-200">
                                    <div className="w-6 h-6 bg-white rounded-full border flex items-center justify-center font-bold text-xs text-gray-500 shrink-0 shadow-sm">{idx + 1}</div>
                                    <div className="flex-1 space-y-3">
                                        <textarea 
                                            className="w-full border p-2 rounded text-sm" 
                                            placeholder="Question to user..." 
                                            value={step.question}
                                            onChange={e=>handleStepChange(idx, 'question', e.target.value)}
                                        />
                                        <div className="flex gap-2">
                                            <input 
                                                className="flex-1 border p-2 rounded text-xs" 
                                                placeholder="Label (e.g. Nama)" 
                                                value={step.label}
                                                onChange={e=>handleStepChange(idx, 'label', e.target.value)}
                                            />
                                            <select 
                                                className="border p-2 rounded text-xs bg-white"
                                                value={step.validation}
                                                onChange={e=>handleStepChange(idx, 'validation', e.target.value)}
                                            >
                                                <option value="text">Text</option>
                                                <option value="number">Number</option>
                                                <option value="email">Email</option>
                                            </select>
                                        </div>
                                    </div>
                                    <button onClick={() => removeStep(idx)} className="text-red-400 hover:text-red-600"><Trash2 className="w-4 h-4"/></button>
                                </div>
                            ))}
                            <button onClick={addStep} className="w-full py-2 border-2 border-dashed rounded-lg text-gray-500 font-bold hover:bg-gray-50 flex items-center justify-center gap-2">
                                <Plus className="w-4 h-4" /> Add Question
                            </button>
                        </div>
                    </div>
                </div>

                <div className="lg:col-span-1">
                    <div className="bg-white p-6 rounded-xl border shadow-sm">
                        <div className="flex justify-between items-center mb-4">
                            <h3 className="font-bold text-gray-800 flex items-center gap-2"><FileText className="w-4 h-4 text-red-500" /> PDF Template</h3>
                            <input 
                                type="checkbox" 
                                checked={data.pdf_config?.enabled} 
                                onChange={e => setData({...data, pdf_config: { ...data.pdf_config, enabled: e.target.checked }})}
                                className="w-4 h-4 cursor-pointer"
                            />
                        </div>
                        
                        {data.pdf_config?.enabled && (
                            <div className="space-y-4 animate-in fade-in">
                                
                                {/* Layout */}
                                <div>
                                    <label className="block text-xs font-bold text-gray-500 uppercase mb-1">Layout</label>
                                    <select 
                                        className="w-full border p-2 rounded text-sm"
                                        value={data.pdf_config.layout || 'portrait'}
                                        onChange={e => setData({...data, pdf_config: {...data.pdf_config, layout: e.target.value}})}
                                    >
                                        <option value="portrait">A4 Document (Portrait)</option>
                                        <option value="card_landscape">Member Card (Landscape)</option>
                                        <option value="ticket">Ticket / Struk (Thermal)</option>
                                    </select>
                                </div>

                                {/* Logo */}
                                <div>
                                    <label className="block text-xs font-bold text-gray-500 uppercase mb-1">Header Logo</label>
                                    <div className="flex items-center gap-2 border p-2 rounded">
                                        <input type="file" accept="image/*" onChange={handleLogoUpload} className="text-xs w-full" />
                                        {data.pdf_config.logo_url && <Image className="w-4 h-4 text-green-500" />}
                                    </div>
                                </div>

                                <div>
                                    <label className="block text-xs font-bold text-gray-500 uppercase mb-1">Document Title</label>
                                    <input className="w-full border p-2 rounded text-sm" value={data.pdf_config.title} onChange={e=>setData({...data, pdf_config: {...data.pdf_config, title: e.target.value}})} />
                                </div>

                                {/* Options */}
                                <div className="space-y-2 bg-gray-50 p-3 rounded border">
                                    <label className="flex items-center gap-2 cursor-pointer">
                                        <input 
                                            type="checkbox" 
                                            checked={data.pdf_config.enable_reg_number}
                                            onChange={e => setData({...data, pdf_config: {...data.pdf_config, enable_reg_number: e.target.checked}})}
                                        />
                                        <span className="text-sm">Auto-generate Reg Number</span>
                                    </label>
                                    <label className="flex items-center gap-2 cursor-pointer">
                                        <input 
                                            type="checkbox" 
                                            checked={data.pdf_config.qr_enabled}
                                            onChange={e => setData({...data, pdf_config: {...data.pdf_config, qr_enabled: e.target.checked}})}
                                        />
                                        <span className="text-sm">Generate QR Code</span>
                                    </label>
                                    {data.pdf_config.qr_enabled && (
                                        <select 
                                            className="w-full border p-1 rounded text-xs mt-1"
                                            value={data.pdf_config.qr_field || ''}
                                            onChange={e => setData({...data, pdf_config: {...data.pdf_config, qr_field: e.target.value}})}
                                        >
                                            <option value="">From Reg Number (Default)</option>
                                            {data.steps.map(s => <option key={s.label} value={s.label}>{s.label}</option>)}
                                        </select>
                                    )}
                                </div>

                                {/* Content Mapping */}
                                <div>
                                    <label className="block text-xs font-bold text-gray-500 uppercase mb-2">Fields to Print</label>
                                    <div className="space-y-1 max-h-32 overflow-y-auto border p-2 rounded">
                                        {data.steps.filter(s => s.label).map(s => (
                                            <div key={s.label} className="flex items-center gap-2 cursor-pointer hover:bg-gray-50 p-1" onClick={() => toggleFieldPrint(s.label)}>
                                                {(data.pdf_config.fields_to_print?.includes(s.label) || !data.pdf_config.fields_to_print?.length) ? <CheckSquare className="w-4 h-4 text-indigo-600" /> : <Square className="w-4 h-4 text-gray-400" />}
                                                <span className="text-sm">{s.label}</span>
                                            </div>
                                        ))}
                                        <p className="text-[10px] text-gray-400 mt-1">If none selected, all fields will be printed.</p>
                                    </div>
                                </div>

                                <div>
                                    <label className="block text-xs font-bold text-gray-500 uppercase mb-1">Footer Text</label>
                                    <input className="w-full border p-2 rounded text-sm" value={data.pdf_config.footer_text} onChange={e=>setData({...data, pdf_config: {...data.pdf_config, footer_text: e.target.value}})} />
                                </div>
                                <div>
                                    <label className="block text-xs font-bold text-gray-500 uppercase mb-1">Closing Message (WA)</label>
                                    <textarea className="w-full border p-2 rounded text-sm h-20" placeholder="Terima kasih..." value={data.pdf_config.closing_message} onChange={e=>setData({...data, pdf_config: {...data.pdf_config, closing_message: e.target.value}})} />
                                </div>
                            </div>
                        )}
                    </div>
                </div>
            </div>
        </div>
    );
}